[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "cd apps/api",
  "npx prisma generate",
  "pnpm build"
]

[start]
cmd = "pnpm start:railway"
