[build]
builder = "nixpacks"
buildCommand = "pnpm install && cd apps/api && pnpm db:generate && pnpm build"

[deploy]
startCommand = "cd apps/api && pnpm db:deploy && pnpm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }

[environments.staging]
variables = { NODE_ENV = "staging" }
